### ISSUE TITLE
WikipediaSummaryService: NullPointerExceptions on invalid page names

### ISSUE THREAD

**Issue by FastLizard4** [LizardNet/LizardIRC-Beancounter#27]
WikipediaSummaryService throws a NullPointerException when given a bad article title (e.g., `?wp #` or a title containing ASCII control codes).  My guess is that it's caused by an unhandled API error.  Relevant stack trace:

```
java.lang.NullPointerException
        at org.lizardirc.beancounter.commands.wikipedia.WikipediaSummaryService.getSummary(WikipediaSummaryService.java:103)
        at org.lizardirc.beancounter.commands.wikipedia.WikipediaSummaryService.getSummary(WikipediaSummaryService.java:57)
        at org.lizardirc.beancounter.commands.wikipedia.WikipediaHandler.summarizeWikiPage(WikipediaHandler.java:94)
        at org.lizardirc.beancounter.commands.wikipedia.WikipediaHandler.handleCommand(WikipediaHandler.java:73)
        at org.lizardirc.beancounter.hooks.MultiCommandHandler.handleCommand(MultiCommandHandler.java:111)
        at org.lizardirc.beancounter.hooks.CommandListener.onGenericMessage(CommandListener.java:74)
        at org.pircbotx.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:157)
        at org.lizardirc.beancounter.hooks.Decorator.onEvent(Decorator.java:49)
        at org.lizardirc.beancounter.hooks.Fantasy.onEvent(Fantasy.java:72)
        at org.lizardirc.beancounter.hooks.Decorator.onEvent(Decorator.java:49)
        at org.lizardirc.beancounter.hooks.Chainable.onEvent(Chainable.java:64)
        at org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:119)
        at org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

(ping @stwalkerster in lieu of proper assignment because space madness)

**Comment by FastLizard4** [comment]
Changeset for review at https://gerrit.fastlizard4.org/r/#/c/257/
